name: Trademarker
version: 1.3.2
main: me.jann.trademarker.Trademarker
api-version: 1.17
commands:
  trademark:
    description: Trademark maps
    aliases:
      - trm
  trademarkreload:
    description: reloads plugin